from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

BASE_DIR = Path(__file__).parent
WORKBOOK_PATH = BASE_DIR / "azure_migrate_dependency_discovery_variations_sample.xlsx"
CONNECTIONS_CSV = BASE_DIR / "dependency_discovery_observed_connections_sample.csv"
PROCESSES_CSV = BASE_DIR / "dependency_discovery_observed_processes_sample.csv"
SUMMARY_CSV = BASE_DIR / "dependency_discovery_summary_sample.csv"
ANNOTATIONS_JSON = BASE_DIR / "dependency_discovery_variation_notes_sample.json"

HEADER_FILL = PatternFill("solid", fgColor="D9EAF7")
HEADER_FONT = Font(bold=True)
ROW_FILLS = {
    "steady-state": PatternFill("solid", fgColor="E8F1FB"),
    "batch-window": PatternFill("solid", fgColor="E8F8F5"),
    "burst": PatternFill("solid", fgColor="FFF2CC"),
    "failover-heartbeat": PatternFill("solid", fgColor="FDEBD0"),
    "external-edge": PatternFill("solid", fgColor="F4ECF7"),
}


def auto_fit_columns(ws):
    for column_cells in ws.columns:
        max_length = 0
        col = get_column_letter(column_cells[0].column)
        for cell in column_cells:
            value = "" if cell.value is None else str(cell.value)
            if len(value) > max_length:
                max_length = len(value)
        ws.column_dimensions[col].width = min(max(max_length + 2, 14), 40)


def write_csv(path: Path, headers: list[str], rows: list[list[str]]):
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(headers)
        writer.writerows(rows)


def add_sheet(wb: Workbook, title: str, headers: list[str], rows: list[list[str]]):
    ws = wb.create_sheet(title)
    ws.append(headers)
    for row in rows:
        ws.append(row)
    for cell in ws[1]:
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(vertical="top", wrap_text=True)
    auto_fit_columns(ws)
    ws.freeze_panes = "A2"
    return ws


def build_process_rows():
    return [
        [
            "enterprise",
            "commerce-java",
            "vm-prod-commerce-java-web-01",
            "web",
            "nginx",
            "Nginx",
            "443",
            "svc_web",
            "web",
            "automatic",
            "running",
            "Steady ingress listener for member and public traffic.",
        ],
        [
            "enterprise",
            "commerce-java",
            "vm-prod-commerce-java-app-01",
            "app",
            "java",
            "Tomcat",
            "8443",
            "svc_java",
            "application",
            "automatic",
            "running",
            "Middle tier handles checkout and catalog APIs.",
        ],
        [
            "enterprise",
            "commerce-java",
            "vm-prod-commerce-java-db-01",
            "db",
            "sqlservr.exe",
            "SQL Server",
            "1433",
            "svc_sql",
            "database",
            "automatic",
            "running",
            "Primary commerce data store.",
        ],
        [
            "enterprise",
            "payments-sqlao",
            "vm-prod-payments-sqlao-api-01",
            "api",
            "dotnet.exe",
            "Payments API",
            "443",
            "svc_pay_api",
            "application",
            "automatic",
            "running",
            "North-south API endpoint for payment initiation.",
        ],
        [
            "enterprise",
            "payments-sqlao",
            "vm-prod-payments-sqlao-dbprima-01",
            "dbprimary",
            "sqlservr.exe",
            "SQL Server Primary",
            "1433;5022",
            "svc_sql",
            "database",
            "automatic",
            "running",
            "Primary SQL Always On replica.",
        ],
        [
            "enterprise",
            "payments-sqlao",
            "vm-prod-payments-sqlao-dbseco-01",
            "dbsecondary",
            "sqlservr.exe",
            "SQL Server Secondary",
            "1433;5022",
            "svc_sql",
            "database",
            "automatic",
            "running",
            "Secondary replica observed receiving HADR traffic.",
        ],
        [
            "enterprise",
            "sap-s4hana",
            "vm-prod-sap-s4hana-sapweb-01",
            "sapweb",
            "sapwebdisp",
            "SAP Web Dispatcher",
            "443",
            "<sid>adm",
            "web",
            "automatic",
            "running",
            "Ingress and routing for SAP web traffic.",
        ],
        [
            "enterprise",
            "sap-s4hana",
            "vm-prod-sap-s4hana-sapapp-01",
            "sapapp",
            "disp+work",
            "SAP App Server",
            "3200;3300",
            "<sid>adm",
            "application",
            "automatic",
            "running",
            "Dialog and RFC processing.",
        ],
        [
            "enterprise",
            "sap-s4hana",
            "vm-prod-sap-s4hana-db-01",
            "db",
            "hdbindexserver",
            "SAP HANA",
            "30015",
            "<sid>adm",
            "database",
            "automatic",
            "running",
            "HANA index server for ERP core.",
        ],
        [
            "enterprise",
            "citrix-vdi",
            "vm-prod-citrix-vdi-contro-01",
            "controller",
            "BrokerService.exe",
            "Citrix Broker Service",
            "80;443",
            "network service",
            "broker",
            "automatic",
            "running",
            "Session brokering and registration.",
        ],
        [
            "enterprise",
            "citrix-vdi",
            "vm-prod-citrix-vdi-storef-01",
            "storefront",
            "Citrix.DeliveryServices",
            "443",
            "network service",
            "web",
            "automatic",
            "running",
            "User storefront and ICA launch.",
        ],
        [
            "enterprise",
            "citrix-vdi",
            "vm-prod-citrix-vdi-worker-01",
            "worker",
            "wfshell.exe",
            "Citrix Session Host",
            "1494;2598",
            "system",
            "session-host",
            "automatic",
            "running",
            "Interactive user-session endpoint with bursty traffic.",
        ],
        [
            "healthcare",
            "ehr-core",
            "vm-prod-ehr-core-web-01",
            "web",
            "IISExpressWorker.exe",
            "EHR Web",
            "443",
            "svc_ehr_web",
            "web",
            "automatic",
            "running",
            "Clinical front end with sustained day-shift usage.",
        ],
        [
            "healthcare",
            "ehr-core",
            "vm-prod-ehr-core-app-01",
            "app",
            "EpicServiceHost.exe",
            "EHR App Tier",
            "8443",
            "svc_ehr_app",
            "application",
            "automatic",
            "running",
            "Application tier with HL7 and API processing.",
        ],
        [
            "healthcare",
            "ehr-core",
            "vm-prod-ehr-core-db-01",
            "db",
            "sqlservr.exe",
            "EHR SQL",
            "1433",
            "svc_sql",
            "database",
            "automatic",
            "running",
            "Transactional clinical data store.",
        ],
        [
            "healthcare",
            "pacs-imaging",
            "vm-prod-pacs-imaging-app-01",
            "app",
            "dicomsvc.exe",
            "PACS DICOM Service",
            "104",
            "svc_pacs",
            "application",
            "automatic",
            "running",
            "DICOM listener with archive fan-out.",
        ],
        [
            "healthcare",
            "pacs-imaging",
            "vm-prod-pacs-imaging-db-01",
            "db",
            "sqlservr.exe",
            "PACS Metadata SQL",
            "1433",
            "svc_sql",
            "database",
            "automatic",
            "running",
            "Imaging metadata repository.",
        ],
        [
            "healthcare",
            "research-genomics",
            "vm-prod-research-genomics-etl-01",
            "etl",
            "python.exe",
            "Genomics ETL",
            "443;22",
            "svc_genomics",
            "data",
            "automatic",
            "running",
            "Scheduled pipeline for ingest and curation.",
        ],
        [
            "healthcare",
            "research-genomics",
            "vm-prod-research-genomics-comput-01",
            "compute",
            "nextflow",
            "Genomics Compute",
            "443;2049",
            "svc_genomics",
            "compute",
            "automatic",
            "running",
            "Bursty compute with batch-heavy observations.",
        ],
        [
            "healthcare",
            "research-genomics",
            "vm-prod-research-genomics-db-01",
            "db",
            "postgres",
            "Research Metadata",
            "5432",
            "svc_pg",
            "database",
            "automatic",
            "running",
            "Metadata and run-state database.",
        ],
    ]


def build_connection_rows():
    return [
        [
            "enterprise",
            "commerce-java",
            "vm-prod-commerce-java-web-01",
            "web",
            "nginx",
            "vm-prod-commerce-java-app-01",
            "vm",
            "app",
            "java",
            "HTTPS",
            "443",
            "tcp",
            "steady-state",
            "24h rolling",
            "180",
            "420",
            "7",
            "980",
            "critical",
            "high",
            "Keep web and app tiers grouped for assessment and cutover sequencing.",
            "Persistent tier-to-tier flow with low latency sensitivity.",
        ],
        [
            "enterprise",
            "commerce-java",
            "vm-prod-commerce-java-app-01",
            "app",
            "java",
            "vm-prod-commerce-java-db-01",
            "vm",
            "db",
            "sqlservr.exe",
            "TDS",
            "1433",
            "tcp",
            "steady-state",
            "24h rolling",
            "95",
            "190",
            "4",
            "620",
            "critical",
            "high",
            "Database proximity and throughput matter for rehost-first planning.",
            "Transaction flow for checkout, catalog, and cart operations.",
        ],
        [
            "enterprise",
            "commerce-java",
            "vm-prod-commerce-java-app-01",
            "app",
            "java",
            "payment-gateway.example",
            "external-service",
            "external",
            "HTTPS endpoint",
            "HTTPS",
            "443",
            "tcp",
            "external-edge",
            "business hours",
            "18",
            "44",
            "28",
            "140",
            "critical",
            "medium",
            "Document internet egress and third-party dependencies before migration.",
            "External PSP/API dependency discovered from app tier.",
        ],
        [
            "enterprise",
            "payments-sqlao",
            "vm-prod-payments-sqlao-api-01",
            "api",
            "dotnet.exe",
            "vm-prod-payments-sqlao-dbprima-01",
            "vm",
            "dbprimary",
            "sqlservr.exe",
            "TDS",
            "1433",
            "tcp",
            "steady-state",
            "24h rolling",
            "120",
            "240",
            "3",
            "740",
            "critical",
            "high",
            "Primary SQL node must remain in same migration wave as API tier.",
            "Primary read/write payment processing flow.",
        ],
        [
            "enterprise",
            "payments-sqlao",
            "vm-prod-payments-sqlao-dbprima-01",
            "dbprimary",
            "sqlservr.exe",
            "vm-prod-payments-sqlao-dbseco-01",
            "vm",
            "dbsecondary",
            "sqlservr.exe",
            "HADR",
            "5022",
            "tcp",
            "failover-heartbeat",
            "24h rolling",
            "40",
            "72",
            "2",
            "310",
            "critical",
            "high",
            "SQL AO replication traffic indicates HA pair semantics for migration runbooks.",
            "Replica synchronization and heartbeat.",
        ],
        [
            "enterprise",
            "payments-sqlao",
            "vm-prod-payments-sqlao-dbseco-01",
            "dbsecondary",
            "sqlservr.exe",
            "vm-prod-payments-sqlao-witnes-01",
            "vm",
            "witness",
            "cluster service",
            "TCP",
            "59999",
            "tcp",
            "failover-heartbeat",
            "24h rolling",
            "12",
            "20",
            "2",
            "42",
            "critical",
            "medium",
            "Witness traffic should be validated during DR and failover test planning.",
            "Witness/quorum coordination.",
        ],
        [
            "enterprise",
            "sap-s4hana",
            "vm-prod-sap-s4hana-sapweb-01",
            "sapweb",
            "sapwebdisp",
            "vm-prod-sap-s4hana-sapapp-01",
            "vm",
            "sapapp",
            "disp+work",
            "HTTPS",
            "443",
            "tcp",
            "steady-state",
            "business hours",
            "130",
            "260",
            "9",
            "760",
            "critical",
            "high",
            "Dispatcher and app servers should remain grouped to preserve response-time characteristics.",
            "North-south SAP UI traffic.",
        ],
        [
            "enterprise",
            "sap-s4hana",
            "vm-prod-sap-s4hana-sapapp-01",
            "sapapp",
            "disp+work",
            "vm-prod-sap-s4hana-db-01",
            "vm",
            "db",
            "hdbindexserver",
            "SQL",
            "30015",
            "tcp",
            "steady-state",
            "business hours",
            "88",
            "170",
            "5",
            "690",
            "critical",
            "high",
            "App-to-HANA latency should be preserved, especially during close periods.",
            "ERP transaction processing against HANA.",
        ],
        [
            "enterprise",
            "sap-s4hana",
            "vm-prod-sap-s4hana-sapapp-01",
            "sapapp",
            "disp+work",
            "vm-prod-sap-s4hana-batch-01",
            "vm",
            "batch",
            "sapbatch",
            "RFC",
            "3300",
            "tcp",
            "batch-window",
            "22:00-04:00",
            "24",
            "88",
            "11",
            "420",
            "critical",
            "medium",
            "Nightly batch windows must be captured for cutover blackout planning.",
            "RFC traffic to background processing tier.",
        ],
        [
            "enterprise",
            "citrix-vdi",
            "vm-prod-citrix-vdi-storef-01",
            "storefront",
            "Citrix.DeliveryServices",
            "vm-prod-citrix-vdi-contro-01",
            "vm",
            "controller",
            "BrokerService.exe",
            "HTTPS",
            "443",
            "tcp",
            "steady-state",
            "business hours",
            "110",
            "240",
            "13",
            "300",
            "critical",
            "high",
            "Control-plane pairing should stay intact during migration sequencing.",
            "StoreFront to Delivery Controller traffic.",
        ],
        [
            "enterprise",
            "citrix-vdi",
            "vm-prod-citrix-vdi-contro-01",
            "controller",
            "BrokerService.exe",
            "vm-prod-citrix-vdi-db-01",
            "vm",
            "db",
            "sqlservr.exe",
            "TDS",
            "1433",
            "tcp",
            "steady-state",
            "24h rolling",
            "42",
            "88",
            "4",
            "160",
            "critical",
            "high",
            "Citrix site database dependency discovered from controller role.",
            "Controller configuration and brokering state.",
        ],
        [
            "enterprise",
            "citrix-vdi",
            "vm-prod-citrix-vdi-worker-01",
            "worker",
            "wfshell.exe",
            "citrix-client-endpoints",
            "external-service",
            "external",
            "ICA/HDX session",
            "ICA",
            "1494",
            "tcp",
            "burst",
            "business hours",
            "220",
            "920",
            "24",
            "450",
            "critical",
            "medium",
            "User session spikes suggest pooled worker behavior and load-balancing requirements.",
            "Representative user-session traffic.",
        ],
        [
            "enterprise",
            "citrix-vdi",
            "vm-prod-citrix-vdi-worker-01",
            "worker",
            "wfshell.exe",
            "profile-share.corp.local",
            "external-service",
            "external",
            "SMB file share",
            "SMB",
            "445",
            "tcp",
            "external-edge",
            "logon/logoff spikes",
            "60",
            "300",
            "16",
            "980",
            "high",
            "medium",
            "User profile, FSLogix, or home-drive paths should be validated before move.",
            "Profile and file-share dependency.",
        ],
        [
            "healthcare",
            "ehr-core",
            "vm-prod-ehr-core-web-01",
            "web",
            "IISExpressWorker.exe",
            "vm-prod-ehr-core-app-01",
            "vm",
            "app",
            "EpicServiceHost.exe",
            "HTTPS",
            "443",
            "tcp",
            "steady-state",
            "day shift",
            "210",
            "360",
            "8",
            "880",
            "critical",
            "high",
            "Sustained clinician usage means front-end and app tiers should move together.",
            "Primary clinician session flow.",
        ],
        [
            "healthcare",
            "ehr-core",
            "vm-prod-ehr-core-app-01",
            "app",
            "EpicServiceHost.exe",
            "vm-prod-ehr-core-db-01",
            "vm",
            "db",
            "sqlservr.exe",
            "TDS",
            "1433",
            "tcp",
            "steady-state",
            "day shift",
            "140",
            "260",
            "4",
            "790",
            "critical",
            "high",
            "Clinical transaction latency and DB affinity are strong migration constraints.",
            "Core charting and order-entry transactions.",
        ],
        [
            "healthcare",
            "ehr-core",
            "vm-prod-ehr-core-app-01",
            "app",
            "EpicServiceHost.exe",
            "adt-broker.corp.local",
            "external-service",
            "external",
            "HL7 broker",
            "MLLP",
            "2575",
            "tcp",
            "steady-state",
            "24h rolling",
            "26",
            "60",
            "10",
            "90",
            "high",
            "medium",
            "Integration engine dependency discovered; keep interface engine readiness in scope.",
            "ADT and interface messaging.",
        ],
        [
            "healthcare",
            "ehr-core",
            "vm-prod-ehr-core-app-01",
            "app",
            "EpicServiceHost.exe",
            "smtp-relay.corp.local",
            "external-service",
            "external",
            "SMTP relay",
            "SMTP",
            "25",
            "tcp",
            "external-edge",
            "business hours",
            "8",
            "18",
            "12",
            "20",
            "medium",
            "low",
            "Low-volume but important operational notification path.",
            "Alerting and outbound notifications.",
        ],
        [
            "healthcare",
            "pacs-imaging",
            "vm-prod-pacs-imaging-app-01",
            "app",
            "dicomsvc.exe",
            "imaging-modalities",
            "external-service",
            "external",
            "DICOM modality",
            "DICOM",
            "104",
            "tcp",
            "burst",
            "care hours",
            "70",
            "180",
            "15",
            "1200",
            "critical",
            "medium",
            "Imaging spikes and device connectivity should be validated before wave planning.",
            "Inbound modality and scanner uploads.",
        ],
        [
            "healthcare",
            "pacs-imaging",
            "vm-prod-pacs-imaging-app-01",
            "app",
            "dicomsvc.exe",
            "vm-prod-pacs-imaging-db-01",
            "vm",
            "db",
            "sqlservr.exe",
            "TDS",
            "1433",
            "tcp",
            "steady-state",
            "24h rolling",
            "34",
            "90",
            "6",
            "140",
            "critical",
            "high",
            "Metadata persistence dependency for imaging workflows.",
            "PACS metadata storage.",
        ],
        [
            "healthcare",
            "pacs-imaging",
            "vm-prod-pacs-imaging-app-01",
            "app",
            "dicomsvc.exe",
            "archive-nas.corp.local",
            "external-service",
            "external",
            "NFS archive",
            "NFS",
            "2049",
            "tcp",
            "batch-window",
            "20:00-06:00",
            "18",
            "72",
            "19",
            "2400",
            "high",
            "medium",
            "Archive backfill and tiering traffic may require dedicated migration window planning.",
            "Nightly image archive tiering.",
        ],
        [
            "healthcare",
            "research-genomics",
            "vm-prod-research-genomics-etl-01",
            "etl",
            "python.exe",
            "sftp-sequencer.partner.example",
            "external-service",
            "external",
            "SFTP feed",
            "SFTP",
            "22",
            "tcp",
            "batch-window",
            "01:00-03:00",
            "10",
            "18",
            "34",
            "820",
            "medium",
            "medium",
            "Sequencer ingest is partner-driven and time-bound.",
            "Nightly FASTQ ingest.",
        ],
        [
            "healthcare",
            "research-genomics",
            "vm-prod-research-genomics-etl-01",
            "etl",
            "python.exe",
            "vm-prod-research-genomics-comput-01",
            "vm",
            "compute",
            "nextflow",
            "HTTPS",
            "443",
            "tcp",
            "batch-window",
            "01:00-07:00",
            "28",
            "110",
            "10",
            "480",
            "medium",
            "high",
            "ETL and compute nodes should be migrated together if batch windows are tight.",
            "Pipeline orchestration and job dispatch.",
        ],
        [
            "healthcare",
            "research-genomics",
            "vm-prod-research-genomics-comput-01",
            "compute",
            "nextflow",
            "reference-data-lake.corp.local",
            "external-service",
            "external",
            "Object storage gateway",
            "HTTPS",
            "443",
            "tcp",
            "burst",
            "batch + ad hoc",
            "44",
            "210",
            "22",
            "3600",
            "medium",
            "medium",
            "High-throughput reads suggest staging or local caching strategy may be needed.",
            "Reference genome and annotation fetches.",
        ],
        [
            "healthcare",
            "research-genomics",
            "vm-prod-research-genomics-comput-01",
            "compute",
            "nextflow",
            "vm-prod-research-genomics-db-01",
            "vm",
            "db",
            "postgres",
            "PostgreSQL",
            "5432",
            "tcp",
            "steady-state",
            "batch + ad hoc",
            "16",
            "40",
            "7",
            "130",
            "medium",
            "high",
            "Run-state metadata dependency for workflow orchestration.",
            "Metadata persistence for jobs and runs.",
        ],
        [
            "shared",
            "shared-services",
            "vm-prod-identity-services-idm-01",
            "idm",
            "lsass.exe",
            "domain-controller.corp.local",
            "external-service",
            "external",
            "Active Directory",
            "LDAP",
            "389",
            "tcp",
            "external-edge",
            "24h rolling",
            "58",
            "120",
            "5",
            "96",
            "critical",
            "high",
            "Identity dependencies often appear across many apps and should be called out in migration readiness reviews.",
            "Representative shared-identity traffic observed from multiple workloads.",
        ],
        [
            "shared",
            "shared-services",
            "vm-prod-monitoring-collector-01",
            "monitoring",
            "telegraf",
            "monitoring-hub.corp.local",
            "external-service",
            "external",
            "Monitoring ingestion",
            "HTTPS",
            "443",
            "tcp",
            "external-edge",
            "24h rolling",
            "42",
            "68",
            "11",
            "52",
            "medium",
            "medium",
            "Operational telemetry egress that should be preserved after migration.",
            "Monitoring and observability traffic.",
        ],
    ]


def build_summary_rows(process_rows, connection_rows):
    counts = defaultdict(
        lambda: {
            "processes": 0,
            "internal": 0,
            "external": 0,
            "patterns": set(),
            "signals": set(),
            "critical": 0,
        }
    )
    for row in process_rows:
        key = (row[0], row[1])
        counts[key]["processes"] += 1
    for row in connection_rows:
        key = (row[0], row[1])
        if row[6] == "external-service":
            counts[key]["external"] += 1
        else:
            counts[key]["internal"] += 1
        counts[key]["patterns"].add(row[12])
        counts[key]["signals"].add(row[20])
        if row[18] == "critical":
            counts[key]["critical"] += 1

    rows = []
    for (scenario, app_name), data in sorted(counts.items()):
        rows.append(
            [
                scenario,
                app_name,
                data["processes"],
                data["internal"],
                data["external"],
                data["critical"],
                "; ".join(sorted(data["patterns"])),
                "; ".join(sorted(data["signals"])),
            ]
        )
    return rows


def build_annotation_payload():
    return {
        "description": "Synthetic Azure Migrate dependency-discovery style sample with multiple workload patterns.",
        "variation_types": [
            "steady-state tier flows",
            "batch-window jobs",
            "burst session traffic",
            "SQL Always On heartbeat and replication",
            "external service edges",
            "healthcare imaging and genomics traffic",
        ],
        "how_to_use": [
            "Use ObservedConnections to discuss what Azure Migrate dependency analysis surfaces at connection level.",
            "Use ObservedProcesses to explain server-side process visibility and listening ports.",
            "Use DiscoverySummary to compare applications by criticality, internal coupling, and external edges.",
        ],
    }


def main():
    process_headers = [
        "scenario",
        "application_name",
        "vm_name",
        "tier",
        "process_name",
        "display_name",
        "listen_ports",
        "run_as",
        "process_category",
        "startup_type",
        "observed_state",
        "notes",
    ]
    connection_headers = [
        "scenario",
        "application_name",
        "source_vm",
        "source_tier",
        "source_process",
        "target_name",
        "target_type",
        "target_tier",
        "target_process",
        "protocol",
        "destination_port",
        "transport",
        "interaction_pattern",
        "observation_window",
        "avg_connections_per_minute",
        "peak_connections_per_minute",
        "avg_rtt_ms",
        "bytes_per_hour_mb",
        "criticality",
        "confidence",
        "migration_signal",
        "notes",
    ]
    summary_headers = [
        "scenario",
        "application_name",
        "process_count",
        "internal_flow_count",
        "external_flow_count",
        "critical_flow_count",
        "observed_patterns",
        "migration_signals",
    ]

    process_rows = build_process_rows()
    connection_rows = build_connection_rows()
    summary_rows = build_summary_rows(process_rows, connection_rows)

    write_csv(PROCESSES_CSV, process_headers, process_rows)
    write_csv(CONNECTIONS_CSV, connection_headers, connection_rows)
    write_csv(SUMMARY_CSV, summary_headers, summary_rows)
    ANNOTATIONS_JSON.write_text(
        json.dumps(build_annotation_payload(), indent=2), encoding="utf-8"
    )

    wb = Workbook()
    wb.remove(wb.active)
    summary_ws = add_sheet(wb, "DiscoverySummary", summary_headers, summary_rows)
    process_ws = add_sheet(wb, "ObservedProcesses", process_headers, process_rows)
    connection_ws = add_sheet(
        wb, "ObservedConnections", connection_headers, connection_rows
    )
    guide_ws = add_sheet(
        wb,
        "VariationGuide",
        ["pattern", "what it shows", "why it matters"],
        [
            [
                "steady-state",
                "Consistent tier-to-tier traffic",
                "Useful for grouping tightly coupled workloads into the same migration wave.",
            ],
            [
                "batch-window",
                "Time-bound nightly or scheduled flows",
                "Highlights blackout windows and cutover timing constraints.",
            ],
            [
                "burst",
                "User-session or ingest spikes",
                "Shows when autoscaling, worker pools, or sequencing matter more than average traffic.",
            ],
            [
                "failover-heartbeat",
                "HA, replication, and quorum flows",
                "Important for SQL AO, clustering, and DR runbooks.",
            ],
            [
                "external-edge",
                "Dependencies on shared services or third parties",
                "Needed for firewall, DNS, identity, and egress planning.",
            ],
        ],
    )

    for ws in [summary_ws, process_ws, connection_ws, guide_ws]:
        for row in ws.iter_rows(min_row=2):
            for cell in row:
                cell.alignment = Alignment(vertical="top", wrap_text=True)
        if ws.title == "ObservedConnections":
            for row in ws.iter_rows(min_row=2):
                fill = ROW_FILLS.get(str(row[12].value), ROW_FILLS["steady-state"])
                for cell in row:
                    cell.fill = fill

    wb.save(WORKBOOK_PATH)
    print(f"Created {WORKBOOK_PATH}")
    print(f"Created {CONNECTIONS_CSV}")
    print(f"Created {PROCESSES_CSV}")
    print(f"Created {SUMMARY_CSV}")
    print(f"Created {ANNOTATIONS_JSON}")


if __name__ == "__main__":
    main()
